// @generated by protoc-gen-es v1.4.2 with parameter "target=ts"
// @generated from file gravity/v1/ethereum_signer.proto (package gravity.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * SignType defines messages that have been signed by an orchestrator
 *
 * @generated from enum gravity.v1.SignType
 */
export enum SignType {
  /**
   * An unspecified type
   *
   * @generated from enum value: SIGN_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * A type for multi-sig updates
   *
   * @generated from enum value: SIGN_TYPE_ORCHESTRATOR_SIGNED_MULTI_SIG_UPDATE = 1;
   */
  ORCHESTRATOR_SIGNED_MULTI_SIG_UPDATE = 1,

  /**
   * A type for batches
   *
   * @generated from enum value: SIGN_TYPE_ORCHESTRATOR_SIGNED_WITHDRAW_BATCH = 2;
   */
  ORCHESTRATOR_SIGNED_WITHDRAW_BATCH = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(SignType)
proto3.util.setEnumType(SignType, "gravity.v1.SignType", [
  { no: 0, name: "SIGN_TYPE_UNSPECIFIED" },
  { no: 1, name: "SIGN_TYPE_ORCHESTRATOR_SIGNED_MULTI_SIG_UPDATE" },
  { no: 2, name: "SIGN_TYPE_ORCHESTRATOR_SIGNED_WITHDRAW_BATCH" },
]);

